### ISSUE TITLE
Add Items to Configuration menu and Add Triggers to Configuration menu does not work with Zabbix 5.4.3

### ISSUE THREAD

**Issue by ihor-chaban** [xenadmin/zabbix-frontend-modules#1]
Hi,
Thank you for these must-have modules.
But I have an issue with two of them.
**Add Items to Configuration menu** and **Add Triggers to Configuration menu** do not work, when I open the corresponding page it shows me the error like this: 
![screenshot_26-08-21_17-16-58](https://user-images.githubusercontent.com/25959371/130979244-df095036-8152-44d2-9ee4-9f4879b2f6ad.png)

Maybe you have ideas on how to fix this?
My Zabbix version is 5.4.3

**Comment by ihor-chaban** [comment]
Both can be fixed by changing the initial URL inside of the modules.

Change **add-items-to-configuration-menu/Module.php**
`->setUrl(new \CUrl('items.php'), 'items.php'))`
to
`->setUrl(new \CUrl('items.php?context=host'), 'items.php?context=host'))`

And the same for **add-triggers-to-configuration-menu/Module.php**

@xenadmin please consider making these changes to your code.

![image](https://user-images.githubusercontent.com/25959371/137192265-23406e50-8e97-45b1-8a22-131831907221.png)

**Comment by ihor-chaban** [comment]
The issue can be closed now.
Hope @xenadmin will add suggested changes later.

**Comment by xenadmin** [comment]
Will take a look on Thursday.

**Comment by xenadmin** [comment]
@ihor-chaban Added your suggestions.
